# Generated by Django 5.1.3 on 2024-11-16 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Image', models.ImageField(upload_to='')),
                ('Brand', models.CharField(blank=True, max_length=100, null=True)),
                ('Category', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.CharField(blank=True, max_length=100, null=True)),
                ('Rating', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('NumReviews', models.IntegerField(blank=True, default=0, null=True)),
                ('Price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('CountInStock', models.IntegerField(blank=True, default=0, null=True)),
                ('CreatedAt', models.DateField(auto_now_add=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
